### PR TITLE
Feature 538: planning update

### PR DESCRIPTION
**Pull request by mz8i**
Work towards #538.

Still missing: 
- disclaimer about checking listed buildings status in official sources
- verification box (need clarification?)

### CODE REVIEW

**Comment by dominijk** [comment]
Looks good, I can see that I only loaded the listed buildings data into production so that explains why there are so few on staging but good to see the locally listed being picked up. I think the grey colour for conservation areas is too subtle on the lighter background map to really pop out. 

One that would be good to wrap into this update would be the auto generation of the Listed building URL to populate the front end as discussed on #160 the list entry is stored in `buildings.planning_list_id` and is `int4` 

@mz8i On the disclaimer do you need more on the wording for this. I can see the dscussion on wording from [Slack](https://colouringlondon.slack.com/archives/CM3PJTHQV/p1578658770028900) thread is superseded by this wording from issue #538   @polly64 can you review and confirm, also I've lost track of whether demolitions is remaining in this category or moving to dynamics?

> Add disclaimer to legend and below sub title that the only authoritative source of listed buildings data is HE and not to rely on CL data for list status or extent of listing
> Disclaimer text: "All data relating to designated buildings should be checked on the National Heritage List for England or local authority websites where used for planning or development purposes"

**Comment by mz8i** [comment]
@dominijk The disclaimer text in the issue above was copied by me from the Slack thread so that we don't have links to external communication but rather all information in this issue. If I missed some later discussion, can you please amend the text here to reflect the final version?

**Comment by polly64** [comment]
@mz8i @dominijk  yes could you use the disclaimer above and then i will show Historic England at meeting on wed morning. At the top of the column if ok?  if we can get all of them loaded by then would be great. @mz8i if  can you possibly swap the white with border to the scheduled monuments to represent conservation so I can have a look and then make the scheduled monuments great with a white border would be great

**Comment by mz8i** [comment]
Now also includes work towards #525 to make it easier to test both on staging

**Comment by polly64** [comment]
@mz8i Re query about demolition - 
Could u add a new separate section below the top 'planning portal link ' box
So it reads 
1. 'Planning Status'
2. 'Designation and Protection' (not 'listing and protection')
Then just keep everything already under the 'Designation & Protection' section as it is

When u open up 'Planning Status' section could u make 4 new boxes:
1. 'Is a planning application live for this site?' (make this inactive) 
2. 'Is demolition proposed?'  (make this live) as a tick box
3. 'Has this application recently been been approved/refused?'  (make this inactive)
4. 'Has the work been carried out? (make this inactive)
Then add a note below this
'For historical planning applications see Planning Portal link' 

Ideally put hover over the first two inactive categories saying 'future proposed live link with Planning portal' but not essential
Move the rest of the demolition section to Dynamics

**Comment by mz8i** [comment]
@polly64 can we move this into a dedicated issue?

**Comment by mz8i** [comment]
@polly64 I will change the names but will keep all the fields in Planning Status inactive - the planned demolition field currently doesn't exist in the database, and I'd like to prevent the size of this piece of work from getting out of hand - can we work on adding / activating that field as part of a separate issue?

**Comment by mz8i** [comment]
@polly64 @dominijk please see staging for latest update of planning and age map. As I have modified the colour scale in both cases (fundamentally in the case of planning), this is just an experiment, and please feel free to say we should revert to the previous options and try tweaking them further.

For Age, I made some further tweaks, while re-using as many of Tarn's colours as possible  (added only one colour - the light blue in the middle).

For Planning, I tried to make it work with the requested colours but couldn't manage to make it look good with small tweaks, so decided to try a completely different approach. I based it on the following reasoning:
- white and gray are difficult to see on either the dark or light background map, so are best avoided
- conservation areas take most space so the colour should be least "aggressive" - chose a light turquoise
- listed buildings are most important (so should contrast with the background of conservation areas - red is good) but grades I, II* and II are levels of the same classification - kept red for Grade I and adopted lighted shades of the same colour for the lower grades
- scheduled monuments also come from the heritage list, but are different than listed buildings - chose yellow
- locally listed buildings are yet another class of objects - chose violet

`#c72e08` Grade I
`#e75b42` Grade II*
`#ffbea1` Grade II
`#ffe59b` Scheduled Monument
`#858ed4` Locally Listed
`#95beba` In Conservation Area

Again this is just a test so all comments welcome. Please let me know if we want to tweak some of these colours or revert to tweaking the previous scheme

**Comment by polly64** [comment]
@mz8i @dominijk hi I can only see one or two listed buildings on staging are they up? I will talk tarn about colours - I just need to get her a screen shot when I can see everything on there- do u think it's just they're not loading on mine or are they not up yet?

**Comment by dominijk** [comment]
@polly64 As earlier comment listed buildings are loaded into production but not staging. So that's why you aren't seeing many. @mz8i and Polly, I think this looks good, some comments below. I agree with raising new issue with order of the boxes on front end. Let's keep this just about colours and what is being coloured;
- Title: in place of planning Statutory protections
- Legend: Move conservation areas higher up as it's the most used
- I'm not sure we will end up with scheduled monuments, these seem to often be geographic boundaries that underly listed buildings

**Comment by mz8i** [comment]
@dominijk any chance we could load the same data to staging? it would help massively in terms of evaluating the colours

**Comment by polly64** [comment]
@mz8i @dominijk also even  i could get a screengrab showing even a small section with all categories coloured in draft and the disclaimer on the key as it is would be great for my grant meeting tomorrow

**Comment by mz8i** [comment]
@polly64 I might copy some data directly from production database to staging so that we have something by tomorrow

**Comment by polly64** [comment]
@mz8i that would be completely brilliant.

**Pull request merged**
