### PR TITLE
Display unverified residential differently

### PR DESCRIPTION
**Pull request by matkoniecz**
Sadly, there is still a remaining issue: verifying building is not causing map to be updated.

Note that `verifyBuildingAttributes` is actually invalidating cache (a bit too eagerly, but I have not investigated that).

@mz8i Do you have any idea what may be going on here?

screen07

### CODE REVIEW

**Comment by matkoniecz** [comment]
Deployed for testing on https://cl-staging.uksouth.cloudapp.azure.com/

**Comment by matkoniecz** [comment]
I missed some extra trigger needed, beyond triggering cache expiry, to redraw map.

Note how verifying fails to change colour (despite logging tile expiry) and how changing building type trigger redraw.

Peek 2021-12-26 04-00

**Comment by matkoniecz** [comment]
@polly64 What you think about colour used and legend description?

**Comment by polly64** [comment]
hi @matkoniecz think the blues need to be better differentiated maybe the verified one significantly lighter?
Sorry didn't quite understand your note above re the problem with changing colour when verified- does your comment mean you're still working on it or you think there is a problem in making it work t all? hope you had great christmas

**Comment by polly64** [comment]
@matkoniecz i realised after we spoke that in the next stage we still also want to find a way of colour visualising which entries (in any of the 12 categories) have been verified and which not, so if you have any thoughts let's chat anytime

**Comment by polly64** [comment]
@matkoniecz don't worry it's fine we can look at this once other stuff complete- it just about looking at ways to show coloured buildings have been verified but i think we need to think and test this over time

**Comment by matkoniecz** [comment]
being replaced by a better PR, will be send soon

**Pull request closed without merging**
